In [1]:
import pandas as pd
pd.__version__

'3.0.5'

Создаю датафрейм:

In [2]:
Data = pd.DataFrame({
    'Name': ['Рома', 'Матвей', 'Дима', 'Ливес', 'Ксюша'],
    'Age': [18, 18, 23, 19, 17],
    'Money': [10000000, 10000, 3123, 999, 0],
    'City': ['Санкт-Петербург', 'Москва', 'Казань', 'Гамбург', 'Москва'],
    'IQ': [145, 55, 100, 122, 90]
})

Data

     Name  Age     Money             City   IQ
0    Рома   18  10000000  Санкт-Петербург  145
1  Матвей   18     10000           Москва   55
2    Дима   23      3123           Казань  100
3   Ливес   19       999          Гамбург  122
4   Ксюша   17         0           Москва   90

Вывожу информацию о Романе через iloc:

In [3]:
RomanInfo = Data.iloc[0, :4]
RomanInfo

Name                Рома
Age                   18
Money           10000000
City     Санкт-Петербург
Name: 0, dtype: object

Вывожу информацию о Матвее через loc:

In [4]:
MatveyInfo = Data.loc[1, 'Name':'City']
MatveyInfo

Name     Матвей
Age          18
Money     10000
City     Москва
Name: 1, dtype: object

Вывожу информацию о богатых:

In [5]:
Rich = Data[Data['Money'] > 1000]
Rich

     Name  Age     Money             City   IQ
0    Рома   18  10000000  Санкт-Петербург  145
1  Матвей   18     10000           Москва   55
2    Дима   23      3123           Казань  100

Групирую инфу о среднем айкью по возврасту:

In [6]:
Smart = Data.groupby('Age').IQ.mean()
Smart

Age
17     90.0
18    100.0
19    122.0
23    100.0
Name: IQ, dtype: float64

Сортирую информацию о богатых:

In [7]:
RichSort = Rich.sort_values(by = 'Money')
RichSort

     Name  Age     Money             City   IQ
2    Дима   23      3123           Казань  100
1  Матвей   18     10000           Москва   55
0    Рома   18  10000000  Санкт-Петербург  145