In [1]:
import pandas as pd, seaborn as sns, sqlite3
from pathlib import Path

Path("../data").mkdir(parents=True, exist_ok=True)
df = sns.load_dataset('titanic')
df.to_csv('../data/titanic.csv', index=False)

df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

Вывести первые 5 строк, только колонки sex, age, fare:
ожидаю 5 строк, 3 колонки

In [2]:
df.loc[:4, ['sex', 'age', 'fare']]

      sex   age     fare
0    male  22.0   7.2500
1  female  38.0  71.2833
2  female  26.0   7.9250
3  female  35.0  53.1000
4    male  35.0   8.0500

Строка с индексом 100 поолностью:
Ожидаю 1 строку;
Оказалось 15 строк так как команда вернула Series

In [3]:
df.loc[100, :]

survived                 0
pclass                   3
sex                 female
age                   28.0
sibsp                    0
parch                    0
fare                7.8958
embarked                 S
class                Third
who                  woman
adult_male           False
deck                   NaN
embark_town    Southampton
alive                   no
alone                 True
Name: 100, dtype: object

Строки с 10 по 15 включительно:
Ожидаю 6 строк

In [4]:
df.loc[10:15, 'sex':'fare']

       sex   age  sibsp  parch     fare
10  female   4.0      1      1  16.7000
11  female  58.0      0      0  26.5500
12    male  20.0      0      0   8.0500
13    male  39.0      1      5  31.2750
14  female  14.0      0      0   7.8542
15  female  55.0      0      0  16.0000

Все посажиры 60 лет:
Не могу предположить результат, потому что не знаю сколько пассажиров страше 60 в талблице

In [5]:
df.loc[df['age'] > 60]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
33,0,2,male,66.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
54,0,1,male,65.0,0,1,61.9792,C,First,man,True,B,Cherbourg,no,False
96,0,1,male,71.0,0,0,34.6542,C,First,man,True,A,Cherbourg,no,True
116,0,3,male,70.5,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
170,0,1,male,61.0,0,0,33.5000,S,First,man,True,B,Southampton,no,True
252,0,1,male,62.0,0,0,26.5500,S,First,man,True,C,Southampton,no,True
275,1,1,female,63.0,1,0,77.9583,S,First,woman,False,D,Southampton,yes,False
280,0,3,male,65.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
326,0,3,male,61.0,0,0,6.2375,S,Third,man,True,NaN,Southampton,no,True
438,0,1,male,64.0,1,4,263.0000,S,First,man,True,C,Southampton,no,False
456,0,1,male,65.0,0,0,26.5500,S,First,man,True,E,Southampton,no,True
483,1,3,female,63.0,0,0,9.5875,S,Third,woman,False,NaN,Southampton,yes,True
493,0,1,male,71.0,0,0,49.5042,C,First,man,True,NaN,Cherbourg,no,True
545,0,1,male,64.0,0,0,26.0000,S,First,man,True,NaN,Southampton,no,True
555,0,1,male,62.0,0,0,26.5500,S,First,man,True,NaN,Southampton,no,True
570,1,2,male,62.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,yes,True
625,0,1,male,61.0,0,0,32.3208,S,First,man,True,D,Southampton,no,True
630,1,1,male,80.0,0,0,30.0000,S,First,man,True,A,Southampton,yes,True
672,0,2,male,70.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
745,0,1,male,70.0,1,1,71.0000,S,First,man,True,B,Southampton,no,False
829,1,1,female,62.0,0,0,80.0000,NaN,First,woman,False,B,NaN,yes,True
851,0,3,male,74.0,0,0,7.7750,S,Third,man,True,NaN,Southampton,no,True

Вывести женщин из 3 класса:
Не могу предположить результат, так как не знаю их количество

In [6]:
df.loc[(df['pclass'] == 3) & (df['sex'] == 'female')]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True
18,0,3,female,31.0,1,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
863,0,3,female,NaN,8,2,69.5500,S,Third,woman,False,NaN,Southampton,no,False
875,1,3,female,15.0,0,0,7.2250,C,Third,child,False,NaN,Cherbourg,yes,True
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False

Вывести пассажиров, севших в Шербуре или Квинстауне - одной операцией, без |:
Не могу ожидать результат, потому что не знаю сколько таких пассажиров в таблице

In [7]:
df[df['embarked'].isin(['C', 'Q'])]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
16,0,3,male,2.0,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False
19,1,3,female,NaN,0,0,7.2250,C,Third,woman,False,NaN,Cherbourg,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
875,1,3,female,15.0,0,0,7.2250,C,Third,child,False,NaN,Cherbourg,yes,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

Сколько пассажиров в каждом классе -- одной командой:
Ожидаю 3 строки, так как в таблице всего 3 класса

In [8]:
df.groupby('pclass').size()

pclass
1    216
2    184
3    491
dtype: int64

Средний и максимальный возраст по полу - одной командой, обе функции сразу:
Ожидаю 2 строки, по среднему и максимальному возрасту на каждый пол

In [9]:
df.groupby('sex')['age'].agg(['mean', 'max'])

             mean   max
sex
female  27.915709  63.0
male    30.726645  80.0

Вывести пять самых дорогих билетов - одной командой без сортировки по всей таблице:
Ожидаю 5 строк раз билетов 5

In [10]:
df['fare'].nlargest(5)

258    512.3292
679    512.3292
737    512.3292
27     263.0000
88     263.0000
Name: fare, dtype: float64

Доля выживших по полу и классу - одной таблицей, где пол по строка, класс по столбцам:
Ожидаю 2 строки раз пол будет по строкам

In [11]:
df.pivot_table(
    index='sex',
    columns='pclass',
    values='survived',
    aggfunc='mean'
)

pclass         1         2         3
sex
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

Первые три строки, все колнки, через позиции, а не метки:
Ожидаю 3 строки

In [12]:
df.iloc[:3, :]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True

Последние 5 строк таблицы:
Ожидаю 5 строк

In [13]:
df.iloc[-5:, :]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

Колонки age и fare для пассажиров, у которых age неизвестен:
Вроде у 177 пассажиров нету возраста, поэтому ожидую 177 строк

In [14]:
df[df['age'].isnull()].loc[:, ['age', 'fare']]

     age     fare
5    NaN   8.4583
17   NaN  13.0000
19   NaN   7.2250
26   NaN   7.2250
28   NaN   7.8792
..   ...      ...
859  NaN   7.2292
863  NaN  69.5500
868  NaN   9.5000
878  NaN   7.8958
888  NaN  23.4500

[177 rows x 2 columns]

Пассажиры дороже 100 и младше 30 одновременно:
Не могу ожидать результат

In [15]:
df[(df['fare'] > 100) & (df['age'] < 30)]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
27,0,1,male,19.00,3,2,263.0000,S,First,man,True,C,Southampton,no,False
88,1,1,female,23.00,3,2,263.0000,S,First,woman,False,C,Southampton,yes,False
118,0,1,male,24.00,0,1,247.5208,C,First,man,True,B,Cherbourg,no,False
297,0,1,female,2.00,1,2,151.5500,S,First,child,False,C,Southampton,no,False
305,1,1,male,0.92,1,2,151.5500,S,First,child,False,C,Southampton,yes,False
307,1,1,female,17.00,1,0,108.9000,C,First,woman,False,C,Cherbourg,yes,False
311,1,1,female,18.00,2,2,262.3750,C,First,woman,False,B,Cherbourg,yes,False
341,1,1,female,24.00,3,2,263.0000,S,First,woman,False,C,Southampton,yes,False
373,0,1,male,22.00,0,0,135.6333,C,First,man,True,NaN,Cherbourg,no,True
377,0,1,male,27.00,0,2,211.5000,C,First,man,True,C,Cherbourg,no,False
393,1,1,female,23.00,1,0,113.2750,C,First,woman,False,D,Cherbourg,yes,False
435,1,1,female,14.00,1,2,120.0000,S,First,child,False,B,Southampton,yes,False
498,0,1,female,25.00,1,2,151.5500,S,First,woman,False,C,Southampton,no,False
505,0,1,male,18.00,1,0,108.9000,C,First,man,True,C,Cherbourg,no,False
550,1,1,male,17.00,0,2,110.8833,C,First,man,True,C,Cherbourg,yes,False
689,1,1,female,15.00,0,1,211.3375,S,First,child,False,B,Southampton,yes,False
700,1,1,female,18.00,1,0,227.5250,C,First,woman,False,C,Cherbourg,yes,False
708,1,1,female,22.00,0,0,151.5500,S,First,woman,False,NaN,Southampton,yes,True
730,1,1,female,29.00,0,0,211.3375,S,First,woman,False,B,Southampton,yes,True
742,1,1,female,21.00,2,2,262.3750,C,First,woman,False,B,Cherbourg,yes,False
802,1,1,male,11.00,1,2,120.0000,S,First,child,False,B,Southampton,yes,False

Пассажиры из 1 и 2 класса - через isin:
Не могу ожидать результат

In [16]:
df[df['pclass'].isin([1, 2])]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

Пассажиры с возрастом от 20 до 40 включительно - не через два условия с &, а одним методом:
Не могу ожидать результат

In [17]:
df[df['age'].between(20, 40)]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

Пассажиры дороже 100 и младше 30 - через query:
Ожидаю 21 строку как в 5

In [18]:
df.query('fare > 100 and age < 30')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
27,0,1,male,19.00,3,2,263.0000,S,First,man,True,C,Southampton,no,False
88,1,1,female,23.00,3,2,263.0000,S,First,woman,False,C,Southampton,yes,False
118,0,1,male,24.00,0,1,247.5208,C,First,man,True,B,Cherbourg,no,False
297,0,1,female,2.00,1,2,151.5500,S,First,child,False,C,Southampton,no,False
305,1,1,male,0.92,1,2,151.5500,S,First,child,False,C,Southampton,yes,False
307,1,1,female,17.00,1,0,108.9000,C,First,woman,False,C,Cherbourg,yes,False
311,1,1,female,18.00,2,2,262.3750,C,First,woman,False,B,Cherbourg,yes,False
341,1,1,female,24.00,3,2,263.0000,S,First,woman,False,C,Southampton,yes,False
373,0,1,male,22.00,0,0,135.6333,C,First,man,True,NaN,Cherbourg,no,True
377,0,1,male,27.00,0,2,211.5000,C,First,man,True,C,Cherbourg,no,False
393,1,1,female,23.00,1,0,113.2750,C,First,woman,False,D,Cherbourg,yes,False
435,1,1,female,14.00,1,2,120.0000,S,First,child,False,B,Southampton,yes,False
498,0,1,female,25.00,1,2,151.5500,S,First,woman,False,C,Southampton,no,False
505,0,1,male,18.00,1,0,108.9000,C,First,man,True,C,Cherbourg,no,False
550,1,1,male,17.00,0,2,110.8833,C,First,man,True,C,Cherbourg,yes,False
689,1,1,female,15.00,0,1,211.3375,S,First,child,False,B,Southampton,yes,False
700,1,1,female,18.00,1,0,227.5250,C,First,woman,False,C,Cherbourg,yes,False
708,1,1,female,22.00,0,0,151.5500,S,First,woman,False,NaN,Southampton,yes,True
730,1,1,female,29.00,0,0,211.3375,S,First,woman,False,B,Southampton,yes,True
742,1,1,female,21.00,2,2,262.3750,C,First,woman,False,B,Cherbourg,yes,False
802,1,1,male,11.00,1,2,120.0000,S,First,child,False,B,Southampton,yes,False

Значение колонки fare с 0 по 4 - двумя способами: через loc и iloc:
Ожидаю 8 строк, по 4 в каждой

In [19]:
df.loc[:4, 'fare']

0     7.2500
1    71.2833
2     7.9250
3    53.1000
4     8.0500
Name: fare, dtype: float64

In [20]:
df.iloc[:5, 6]

0     7.2500
1    71.2833
2     7.9250
3    53.1000
4     8.0500
Name: fare, dtype: float64

Скопируй в переменную child только пассажиров младше 16 так, чтобы при последующем изменении child не прилетело предупреждении о копии:
Ожидаю переменную при изменении которой не будет предупреждений о копии

In [21]:
child = df[df['age'] < 16]
child.loc[7, 'pclass'] = 4
child

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
7,0,4,male,2.00,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
9,1,2,female,14.00,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
10,1,3,female,4.00,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
14,0,3,female,14.00,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True
16,0,3,male,2.00,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
831,1,2,male,0.83,1,1,18.7500,S,Second,child,False,NaN,Southampton,yes,False
850,0,3,male,4.00,4,2,31.2750,S,Third,child,False,NaN,Southampton,no,False
852,0,3,female,9.00,1,1,15.2458,C,Third,child,False,NaN,Cherbourg,no,False
869,1,3,male,4.00,1,1,11.1333,S,Third,child,False,NaN,Southampton,yes,False
875,1,3,female,15.00,0,0,7.2250,C,Third,child,False,NaN,Cherbourg,yes,True

Сколько пассажиров каждого пола:
Ожидаю 2 строки

In [22]:
df['sex'].value_counts()

sex
male      577
female    314
Name: count, dtype: int64

То же самое но в долях, а не в штуках:
Ожидаю 2 строки

In [23]:
df['sex'].value_counts(normalize=True)

sex
male      0.647587
female    0.352413
Name: proportion, dtype: float64

Выживаемости по полу и классу сразу:
Ожидаю 6 строк

In [24]:
df.groupby(by=['sex', 'pclass'])['survived'].mean()

sex     pclass
female  1         0.968085
        2         0.921053
        3         0.500000
male    1         0.368852
        2         0.157407
        3         0.135447
Name: survived, dtype: float64

По каждому классу: средний возраст, максимальная цена билета и число пассажиров - одной командой:
Ожидаю 3 строки

In [25]:
df.groupby('pclass').agg(mean_age=('age', 'mean'), max_fare=('fare', 'max'), total=('pclass', 'size'))

         mean_age  max_fare  total
pclass
1       38.233441  512.3292    216
2       29.877630   73.5000    184
3       25.140620   69.5500    491

Прошлый результат, но чтобы pclass был обычной колонкой:
Ожидаю 3 строки

In [26]:
df.groupby('pclass', as_index=False).agg(mean_age=('age', 'mean'), max_fare=('fare', 'max'), total=('pclass', 'size'))

   pclass   mean_age  max_fare  total
0       1  38.233441  512.3292    216
1       2  29.877630   73.5000    184
2       3  25.140620   69.5500    491

Три класса отсортированные по средней цене билета от большей к меньшей:
Ожидаю 3 строки

In [27]:
df.groupby('pclass')['fare'].mean().sort_values(ascending=False)

pclass
1    84.154687
2    20.662183
3    13.675550
Name: fare, dtype: float64

Добавить колонку fare_rank - место пассажира по цене
Ожидаю увидеть еще одну колонку в таблице

In [28]:
df['fare_rank'] = df.groupby('pclass')['fare'].transform(lambda x: x.rank(ascending=False, method='min'))
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,fare_rank
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,421.0
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,98.0
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,263.0
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,121.0
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,219.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,101.0
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,170.0
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,65.0
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,170.0
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,364.0

Добавить колонку age_group с интерваллами возраста: до 16, 16-32, 32-64, старше. Одним методом:
Ожидаю новый столбик в таблице

In [29]:
df['age_group'] = pd.cut(
    df['age'],
    bins=[0, 16, 32, 64, float('inf')],
    labels=['до 16', '16-32', '32-64', 'старше 64']
)
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,fare_rank,age_group
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,421.0,16-32
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,98.0,32-64
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,263.0,16-32
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,121.0,32-64
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,219.0,32-64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,101.0,16-32
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,170.0,16-32
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,65.0,NaN
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,170.0,16-32
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,364.0,16-32

Выживаемость по каждой возрастной группе:
Ожидаю 4 строки

In [30]:
df.groupby('age_group')['survived'].agg(['mean', 'count'])

               mean  count
age_group
до 16      0.550000    100
16-32      0.369942    346
32-64      0.412451    257
старше 64  0.090909     11

Пассажиры, чья цена билета выше средней по их классу:
Не могу ожидать результат

In [31]:
df[df['fare'] > df.groupby('pclass')['fare'].transform('mean')]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,fare_rank,age_group
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False,74.0,до 16
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False,23.0,до 16
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False,101.0,до 16
13,0,3,male,39.0,1,5,31.2750,S,Third,man,True,NaN,Southampton,no,False,35.0,32-64
16,0,3,male,2.0,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False,42.0,до 16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
863,0,3,female,NaN,8,2,69.5500,S,Third,woman,False,NaN,Southampton,no,False,1.0,NaN
874,1,2,female,28.0,1,0,24.0000,C,Second,woman,False,NaN,Cherbourg,yes,False,69.0,16-32
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False,40.0,16-32
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False,42.0,32-64
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,65.0,NaN

In [32]:
conn = sqlite3.connect("../sql/shop.db")
orders = pd.read_sql("SELECT * FROM orders", conn)
customers = pd.read_sql("SELECT * FROM customers", conn)

Соединяю имена с их заказами:
Ожидаю 39 строк

In [33]:
orders.merge(customers, left_on='customer_id', right_on='id', how='inner').loc[:, ['name', 'id_x']]

       name  id_x
0    Андрей     1
1     Артур     2
2      Маша     3
3   Мухамед     4
4      Гоша     5
5      Гоша     6
6   Мухамед     7
7     Артур     8
8    Никита    10
9   Мухамед    11
10    Артур    12
11     Маша    13
12   Андрей    14
13  Мухамед    15
14    Павел    16
15   Никита    17
16     Маша    18
17    Артур    19
18  Мухамед    20
19  Мухамед    21
20    Артур    22
21    Павел    23
22  Мухамед    24
23   Андрей    25
24  Мухамед    26
25     Гоша    27
26   Андрей    28
27    Артур    29
28     Гоша    30
29  Мухамед    31
30     Гоша    32
31   Андрей    33
32     Маша    34
33   Андрей    35
34   Никита    36
35  Мухамед    37
36    Павел    38
37    Артур    39
38   Никита    40

Все клиенты со своими заказами включая тех, у которых нет заказа:
Ожидаю 40 строк

In [34]:
customers.merge(orders, left_on='id', right_on='customer_id', how='left')

,id_x,name,city,signup_date,id_y,customer_id,amount,order_date
0,1,Андрей,Токио,2024-04-24,1.0,1.0,4444.896554,2026-06-26
1,1,Андрей,Токио,2024-04-24,14.0,1.0,1627.465971,2026-06-05
2,1,Андрей,Токио,2024-04-24,25.0,1.0,7890.551337,2026-07-01
3,1,Андрей,Токио,2024-04-24,28.0,1.0,1233.847728,2025-04-08
4,1,Андрей,Токио,2024-04-24,33.0,1.0,4423.502153,2026-11-19
5,1,Андрей,Токио,2024-04-24,35.0,1.0,677.197143,2025-06-13
6,2,Маша,Париж,2025-12-17,3.0,2.0,9758.661281,2025-03-07
7,2,Маша,Париж,2025-12-17,13.0,2.0,4720.537937,2025-12-15
8,2,Маша,Париж,2025-12-17,18.0,2.0,1386.222903,2026-04-26
9,2,Маша,Париж,2025-12-17,34.0,2.0,4144.433573,2026-11-26
10,3,Никита,Стамбул,2026-02-01,10.0,3.0,7605.068627,2026-03-19
11,3,Никита,Стамбул,2026-02-01,17.0,3.0,4748.602532,2026-07-11
12,3,Никита,Стамбул,2026-02-01,36.0,3.0,3006.578202,2025-11-01
13,3,Никита,Стамбул,2026-02-01,40.0,3.0,991.473822,2025-01-16
14,4,Артур,Лондон,2025-01-30,2.0,4.0,7003.943488,2026-08-25
15,4,Артур,Лондон,2025-01-30,8.0,4.0,2349.663346,2025-03-06
16,4,Артур,Лондон,2025-01-30,12.0,4.0,7805.996621,2026-09-18
17,4,Артур,Лондон,2025-01-30,19.0,4.0,2346.402556,2026-01-31
18,4,Артур,Лондон,2025-01-30,22.0,4.0,3936.035952,2026-07-18
19,4,Артур,Лондон,2025-01-30,29.0,4.0,4763.852441,2026-04-13
20,4,Артур,Лондон,2025-01-30,39.0,4.0,1753.031907,2026-07-24
21,5,Гоша,Москва,2024-04-12,5.0,5.0,4558.820785,2025-03-31
22,5,Гоша,Москва,2024-04-12,6.0,5.0,9274.973390,2025-09-17
23,5,Гоша,Москва,2024-04-12,27.0,5.0,5730.537840,2025-11-18
24,5,Гоша,Москва,2024-04-12,30.0,5.0,7673.488688,2026-02-07
25,5,Гоша,Москва,2024-04-12,32.0,5.0,3109.105971,2026-02-26
26,6,Мухамед,Париж,2025-11-30,4.0,6.0,7882.036622,2026-06-17
27,6,Мухамед,Париж,2025-11-30,7.0,6.0,8245.339971,2026-01-17
28,6,Мухамед,Париж,2025-11-30,11.0,6.0,9709.910442,2025-09-06
29,6,Мухамед,Париж,2025-11-30,15.0,6.0,7473.145343,2025-09-14
30,6,Мухамед,Париж,2025-11-30,20.0,6.0,4427.803997,2025-04-23
31,6,Мухамед,Париж,2025-11-30,21.0,6.0,3192.429750,2026-05-06
32,6,Мухамед,Париж,2025-11-30,24.0,6.0,2079.091205,2025-04-08
33,6,Мухамед,Париж,2025-11-30,26.0,6.0,7081.137248,2025-07-13
34,6,Мухамед,Париж,2025-11-30,31.0,6.0,5580.436067,2025-03-05
35,6,Мухамед,Париж,2025-11-30,37.0,6.0,5614.618308,2025-12-20
36,7,Никита,Москва,2023-01-02,NaN,NaN,NaN,NaN
37,8,Павел,NaN,2026-03-15,16.0,8.0,3325.671046,2026-09-26
38,8,Павел,NaN,2026-03-15,23.0,8.0,6856.705489,2025-07-21
39,8,Павел,NaN,2026-03-15,38.0,8.0,4123.229928,2026-04-11

При помощи слияния найти клиента без заказов:
Ожидаю 8 строк, так как прийдет Series

In [35]:
customers.merge(orders, left_on='id', right_on='customer_id', how='left').sort_values('customer_id').iloc[-1, :]

id_x                    7
name               Никита
city               Москва
signup_date    2023-01-02
id_y                  NaN
customer_id           NaN
amount                NaN
order_date            NaN
Name: 36, dtype: object

In [36]:
rl_df = orders.merge(customers, left_on='customer_id', right_on='id', how='left')
rl_df[rl_df['id_y'].isnull()]

   id_x  customer_id      amount  order_date  id_y name city signup_date
8     9          999  731.790835  2026-01-24   NaN  NaN  NaN         NaN

Имена всех клиентов и сумма всех их заказов:
Ожидаю 7 строк

In [37]:
customers.merge(orders, left_on='id', right_on='customer_id', how='left').groupby('name')['amount'].sum()

name
Андрей     20297.460886
Артур      29958.926310
Гоша       30346.926674
Маша       20009.855694
Мухамед    61285.948953
Никита     16351.723182
Павел      14305.606463
Name: amount, dtype: float64

У merge есть параметр, который проверяет ожидаемую кратность связи и падает с ошибкой, если ключ оказался неуникальным там, где ты этого не ждал. Найди его и примени к задаче 2, объявив, что связь «многие к одному». Потом попробуй объявить «один к одному» и посмотри, что произойдёт

In [38]:
orders.merge(customers, left_on='customer_id', right_on='id', how='inner', validate='m:1')

,id_x,customer_id,amount,order_date,id_y,name,city,signup_date
0,1,1,4444.896554,2026-06-26,1,Андрей,Токио,2024-04-24
1,2,4,7003.943488,2026-08-25,4,Артур,Лондон,2025-01-30
2,3,2,9758.661281,2025-03-07,2,Маша,Париж,2025-12-17
3,4,6,7882.036622,2026-06-17,6,Мухамед,Париж,2025-11-30
4,5,5,4558.820785,2025-03-31,5,Гоша,Москва,2024-04-12
5,6,5,9274.973390,2025-09-17,5,Гоша,Москва,2024-04-12
6,7,6,8245.339971,2026-01-17,6,Мухамед,Париж,2025-11-30
7,8,4,2349.663346,2025-03-06,4,Артур,Лондон,2025-01-30
8,10,3,7605.068627,2026-03-19,3,Никита,Стамбул,2026-02-01
9,11,6,9709.910442,2025-09-06,6,Мухамед,Париж,2025-11-30
10,12,4,7805.996621,2026-09-18,4,Артур,Лондон,2025-01-30
11,13,2,4720.537937,2025-12-15,2,Маша,Париж,2025-12-17
12,14,1,1627.465971,2026-06-05,1,Андрей,Токио,2024-04-24
13,15,6,7473.145343,2025-09-14,6,Мухамед,Париж,2025-11-30
14,16,8,3325.671046,2026-09-26,8,Павел,NaN,2026-03-15
15,17,3,4748.602532,2026-07-11,3,Никита,Стамбул,2026-02-01
16,18,2,1386.222903,2026-04-26,2,Маша,Париж,2025-12-17
17,19,4,2346.402556,2026-01-31,4,Артур,Лондон,2025-01-30
18,20,6,4427.803997,2025-04-23,6,Мухамед,Париж,2025-11-30
19,21,6,3192.429750,2026-05-06,6,Мухамед,Париж,2025-11-30
20,22,4,3936.035952,2026-07-18,4,Артур,Лондон,2025-01-30
21,23,8,6856.705489,2025-07-21,8,Павел,NaN,2026-03-15
22,24,6,2079.091205,2025-04-08,6,Мухамед,Париж,2025-11-30
23,25,1,7890.551337,2026-07-01,1,Андрей,Токио,2024-04-24
24,26,6,7081.137248,2025-07-13,6,Мухамед,Париж,2025-11-30
25,27,5,5730.537840,2025-11-18,5,Гоша,Москва,2024-04-12
26,28,1,1233.847728,2025-04-08,1,Андрей,Токио,2024-04-24
27,29,4,4763.852441,2026-04-13,4,Артур,Лондон,2025-01-30
28,30,5,7673.488688,2026-02-07,5,Гоша,Москва,2024-04-12
29,31,6,5580.436067,2025-03-05,6,Мухамед,Париж,2025-11-30
30,32,5,3109.105971,2026-02-26,5,Гоша,Москва,2024-04-12
31,33,1,4423.502153,2026-11-19,1,Андрей,Токио,2024-04-24
32,34,2,4144.433573,2026-11-26,2,Маша,Париж,2025-12-17
33,35,1,677.197143,2025-06-13,1,Андрей,Токио,2024-04-24
34,36,3,3006.578202,2025-11-01,3,Никита,Стамбул,2026-02-01
35,37,6,5614.618308,2025-12-20,6,Мухамед,Париж,2025-11-30
36,38,8,4123.229928,2026-04-11,8,Павел,NaN,2026-03-15
37,39,4,1753.031907,2026-07-24,4,Артур,Лондон,2025-01-30
38,40,3,991.473822,2025-01-16,3,Никита,Стамбул,2026-02-01

1 к 1 падает с ошшибкой поэтому я убрал, а m:1 ничего не меняет, просто провалидировал

У merge есть параметр, который добавляет колонку с пометкой, из какой таблицы пришла строка: только слева, только справа или из обеих. Найди его и примени к задаче 3 — увидишь клиента без заказов сразу, без отдельного запроса

In [39]:
customers.merge(orders, left_on='id', right_on='customer_id', how='left', indicator=True)

,id_x,name,city,signup_date,id_y,customer_id,amount,order_date,_merge
0,1,Андрей,Токио,2024-04-24,1.0,1.0,4444.896554,2026-06-26,both
1,1,Андрей,Токио,2024-04-24,14.0,1.0,1627.465971,2026-06-05,both
2,1,Андрей,Токио,2024-04-24,25.0,1.0,7890.551337,2026-07-01,both
3,1,Андрей,Токио,2024-04-24,28.0,1.0,1233.847728,2025-04-08,both
4,1,Андрей,Токио,2024-04-24,33.0,1.0,4423.502153,2026-11-19,both
5,1,Андрей,Токио,2024-04-24,35.0,1.0,677.197143,2025-06-13,both
6,2,Маша,Париж,2025-12-17,3.0,2.0,9758.661281,2025-03-07,both
7,2,Маша,Париж,2025-12-17,13.0,2.0,4720.537937,2025-12-15,both
8,2,Маша,Париж,2025-12-17,18.0,2.0,1386.222903,2026-04-26,both
9,2,Маша,Париж,2025-12-17,34.0,2.0,4144.433573,2026-11-26,both
10,3,Никита,Стамбул,2026-02-01,10.0,3.0,7605.068627,2026-03-19,both
11,3,Никита,Стамбул,2026-02-01,17.0,3.0,4748.602532,2026-07-11,both
12,3,Никита,Стамбул,2026-02-01,36.0,3.0,3006.578202,2025-11-01,both
13,3,Никита,Стамбул,2026-02-01,40.0,3.0,991.473822,2025-01-16,both
14,4,Артур,Лондон,2025-01-30,2.0,4.0,7003.943488,2026-08-25,both
15,4,Артур,Лондон,2025-01-30,8.0,4.0,2349.663346,2025-03-06,both
16,4,Артур,Лондон,2025-01-30,12.0,4.0,7805.996621,2026-09-18,both
17,4,Артур,Лондон,2025-01-30,19.0,4.0,2346.402556,2026-01-31,both
18,4,Артур,Лондон,2025-01-30,22.0,4.0,3936.035952,2026-07-18,both
19,4,Артур,Лондон,2025-01-30,29.0,4.0,4763.852441,2026-04-13,both
20,4,Артур,Лондон,2025-01-30,39.0,4.0,1753.031907,2026-07-24,both
21,5,Гоша,Москва,2024-04-12,5.0,5.0,4558.820785,2025-03-31,both
22,5,Гоша,Москва,2024-04-12,6.0,5.0,9274.973390,2025-09-17,both
23,5,Гоша,Москва,2024-04-12,27.0,5.0,5730.537840,2025-11-18,both
24,5,Гоша,Москва,2024-04-12,30.0,5.0,7673.488688,2026-02-07,both
25,5,Гоша,Москва,2024-04-12,32.0,5.0,3109.105971,2026-02-26,both
26,6,Мухамед,Париж,2025-11-30,4.0,6.0,7882.036622,2026-06-17,both
27,6,Мухамед,Париж,2025-11-30,7.0,6.0,8245.339971,2026-01-17,both
28,6,Мухамед,Париж,2025-11-30,11.0,6.0,9709.910442,2025-09-06,both
29,6,Мухамед,Париж,2025-11-30,15.0,6.0,7473.145343,2025-09-14,both
30,6,Мухамед,Париж,2025-11-30,20.0,6.0,4427.803997,2025-04-23,both
31,6,Мухамед,Париж,2025-11-30,21.0,6.0,3192.429750,2026-05-06,both
32,6,Мухамед,Париж,2025-11-30,24.0,6.0,2079.091205,2025-04-08,both
33,6,Мухамед,Париж,2025-11-30,26.0,6.0,7081.137248,2025-07-13,both
34,6,Мухамед,Париж,2025-11-30,31.0,6.0,5580.436067,2025-03-05,both
35,6,Мухамед,Париж,2025-11-30,37.0,6.0,5614.618308,2025-12-20,both
36,7,Никита,Москва,2023-01-02,NaN,NaN,NaN,NaN,left_only
37,8,Павел,NaN,2026-03-15,16.0,8.0,3325.671046,2026-09-26,both
38,8,Павел,NaN,2026-03-15,23.0,8.0,6856.705489,2025-07-21,both
39,8,Павел,NaN,2026-03-15,38.0,8.0,4123.229928,2026-04-11,both

При помощи этого параметра можно заметить единственную строку, которая пришла только из левой таблицы и которая является ответом

Средняя цена билета по классу и порту посадки: класс по строкам, порт по столбцам:
Ожидаю 3 строки

In [40]:
df.pivot_table(
    index='pclass',
    columns='embarked',
    values='fare',
    aggfunc='mean',
    margins=True,
    margins_name='total'
)

embarked           C          Q          S      total
pclass
1         104.718529  90.000000  70.364862  84.193516
2          25.358335  12.350000  20.327439  20.662183
3          11.214083  11.183393  14.644083  13.675550
total      59.954144  13.276030  27.079812  32.096681

Число пассажиров по полу и классу — через crosstab, не через pivot_table:
Ожидаю 2 строки

In [41]:
pd.crosstab(df['sex'], df['pclass'])

pclass    1    2    3
sex
female   94   76  144
male    122  108  347

То же в долях от общего числа — одним аргументом:
Ожидаю 2 строки

In [42]:
pd.crosstab(df['sex'], df['pclass'], normalize=True)

pclass         1         2         3
sex
female  0.105499  0.085297  0.161616
male    0.136925  0.121212  0.389450

То же, но в долях внутри каждой строки: какая часть женщин пришлась на каждый класс:
Ожидаю 2 строки

In [43]:
pd.crosstab(df['sex'], df['pclass'], normalize='columns')

pclass         1         2         3
sex
female  0.435185  0.413043  0.293279
male    0.564815  0.586957  0.706721

Сводная таблица с двумя уровнями по строкам: класс и пол, значение — средняя выживаемость:
Ожидаю 6 строк

In [44]:
df.pivot_table(
    values='survived',
    index=['pclass', 'sex'],
    aggfunc='mean'
)

               survived
pclass sex
1      female  0.968085
       male    0.368852
2      female  0.921053
       male    0.157407
3      female  0.500000
       male    0.135447

Вопрос без кода: чем crosstab отличается от pivot_table?
Ответ: Первое что я заметил crosstab по умолчанию счиатет количество просто или можно задать среднее значение, когда в pivot_table можно передать разынае функции. Второе, crosstab вызываеется как метод pandas и в него передаются Series, а в pivot_table вызывается как метод DataFrame и в него передаются уже его индексы

Все пассажирки старше 50, только колонки age, fare, class:
Не могу ожидать результат

In [45]:
df[(df['sex'] == 'female') & (df['age'] > 50)].loc[:, ['age', 'fare', 'class']]

      age      fare   class
11   58.0   26.5500   First
15   55.0   16.0000  Second
195  58.0  146.5208   First
268  58.0  153.4625   First
275  63.0   77.9583   First
366  60.0   75.2500   First
483  63.0    9.5875   Third
496  54.0   78.2667   First
513  54.0   59.4000   First
571  53.0   51.4792   First
591  52.0   78.2667   First
765  51.0   77.9583   First
772  57.0   10.5000  Second
774  54.0   23.0000  Second
820  52.0   93.5000   First
829  62.0   80.0000   First
879  56.0   83.1583   First

Пять самых молодых пассажиров первого класса, целыми строками:
Ожидаю 5 строк

In [46]:
df[df['pclass'] == 1].nsmallest(5, 'age')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,fare_rank,age_group
305,1,1,male,0.92,1,2,151.5500,S,First,child,False,C,Southampton,yes,False,26.0,до 16
297,0,1,female,2.00,1,2,151.5500,S,First,child,False,C,Southampton,no,False,26.0,до 16
445,1,1,male,4.00,0,2,81.8583,S,First,child,False,A,Southampton,yes,False,74.0,до 16
802,1,1,male,11.00,1,2,120.0000,S,First,child,False,B,Southampton,yes,False,39.0,до 16
435,1,1,female,14.00,1,2,120.0000,S,First,child,False,B,Southampton,yes,False,39.0,до 16

Средняя цена билета отдельно для выживших и погибших, в каждом классе — одной таблицей:
Ожидаю 6 строк

In [47]:
df.pivot_table(
    index=['survived', 'pclass'],
    values='fare',
    aggfunc='mean'
)

                      fare
survived pclass
0        1       64.684007
         2       19.412328
         3       13.669364
1        1       95.608029
         2       22.055700
         3       13.694887

Сколько человек в каждой комбинации «пол + порт посадки»:
Ожидаю 6 строк

In [48]:
df.groupby(by=['sex', 'embarked']).size()

sex     embarked
female  C            73
        Q            36
        S           203
male    C            95
        Q            41
        S           441
dtype: int64

Доля выживших среди тех, кто путешествовал один, и среди остальных:
Ожидаю 2 строки

In [49]:
df.groupby('alone')['survived'].mean()

alone
False    0.505650
True     0.303538
Name: survived, dtype: float64

Добавь колонку family_size — сколько всего родственников на борту у пассажира, включая его самого
Ожидаю добавление одной колонки

In [50]:
df['family_size'] = 1 + df['sibsp'] + df['parch']
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,fare_rank,age_group,family_size
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,421.0,16-32,2
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,98.0,32-64,2
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,263.0,16-32,1
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,121.0,32-64,2
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,219.0,32-64,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,101.0,16-32,1
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,170.0,16-32,1
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,65.0,NaN,4
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,170.0,16-32,1
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,364.0,16-32,1

Средняя выживаемость по family_size, только для размеров, встречающихся хотя бы у 10 человек:
Не могу ожидать результат

In [51]:
df.groupby('family_size').filter(lambda x: len(x) > 10).groupby('family_size')['survived'].mean()

family_size
1    0.303538
2    0.552795
3    0.578431
4    0.724138
5    0.200000
6    0.136364
7    0.333333
Name: survived, dtype: float64

Пассажиры, чей возраст выше среднего по их классу и полу одновременно:
Не могу ожидать результат

In [52]:
df[(df['age'] > df.groupby('pclass')['age'].transform('mean')) & (df['age'] > df.groupby('sex')['age'].transform('mean'))]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,fare_rank,age_group,family_size
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,219.0,32-64,1
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True,136.0,32-64,1
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True,185.0,32-64,1
13,0,3,male,39.0,1,5,31.2750,S,Third,man,True,NaN,Southampton,no,False,35.0,32-64,7
15,1,2,female,55.0,0,0,16.0000,S,Second,woman,False,NaN,Southampton,yes,True,86.0,32-64,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
873,0,3,male,47.0,0,0,9.0000,S,Third,man,True,NaN,Southampton,no,True,191.0,32-64,1
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False,69.0,32-64,2
881,0,3,male,33.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True,281.0,32-64,1
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False,42.0,32-64,6
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,364.0,16-32,1

Собери отдельную таблицу-справочник: класс и его словесное описание (1 → Люкс, 2 → Средний, 3 → Эконом). Присоедини её к основной так, чтобы описание появилось колонкой.

In [53]:
classes = pd.DataFrame({
    'id': [1, 2, 3],
    'Names': ['Luxe', 'Mid', 'Econom']
})

df = df.merge(classes, left_on='pclass', right_on='id', how='left')
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,fare_rank,age_group,family_size,id,Names
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,421.0,16-32,2,3,Econom
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,98.0,32-64,2,1,Luxe
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,263.0,16-32,1,3,Econom
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,121.0,32-64,2,1,Luxe
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,219.0,32-64,1,3,Econom
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,101.0,16-32,1,2,Mid
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,170.0,16-32,1,1,Luxe
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,65.0,NaN,4,3,Econom
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,170.0,16-32,1,1,Luxe
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,364.0,16-32,1,3,Econom

Проверь при соединении из задачи 9, что связь «многие к одному», штатным параметром.

In [54]:
df.merge(classes, left_on='pclass', right_on='id', how='left', validate='m:1')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,...,embark_town,alive,alone,fare_rank,age_group,family_size,id_x,Names_x,id_y,Names_y
0,0,3,male,22.0,1,0,7.2500,S,Third,man,...,Southampton,no,False,421.0,16-32,2,3,Econom,3,Econom
1,1,1,female,38.0,1,0,71.2833,C,First,woman,...,Cherbourg,yes,False,98.0,32-64,2,1,Luxe,1,Luxe
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,...,Southampton,yes,True,263.0,16-32,1,3,Econom,3,Econom
3,1,1,female,35.0,1,0,53.1000,S,First,woman,...,Southampton,yes,False,121.0,32-64,2,1,Luxe,1,Luxe
4,0,3,male,35.0,0,0,8.0500,S,Third,man,...,Southampton,no,True,219.0,32-64,1,3,Econom,3,Econom
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,...,Southampton,no,True,101.0,16-32,1,2,Mid,2,Mid
887,1,1,female,19.0,0,0,30.0000,S,First,woman,...,Southampton,yes,True,170.0,16-32,1,1,Luxe,1,Luxe
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,...,Southampton,no,False,65.0,NaN,4,3,Econom,3,Econom
889,1,1,male,26.0,0,0,30.0000,C,First,man,...,Cherbourg,yes,True,170.0,16-32,1,1,Luxe,1,Luxe
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,...,Queenstown,no,True,364.0,16-32,1,3,Econom,3,Econom

Три порта, отсортированные по доле выживших, с указанием числа пассажиров в каждом:
Не могу ожидать результат

In [55]:
df.groupby('embark_town')['survived'].agg(
    mean_survived='mean',
    count_passangers='count'
).sort_values(by='mean_survived', ascending=False)

             mean_survived  count_passangers
embark_town
Cherbourg         0.553571               168
Queenstown        0.389610                77
Southampton       0.336957               644

In [56]:
df.loc[df.groupby('pclass')['fare'].idxmax(), ['pclass', 'fare', 'age', 'sex']].set_index('pclass')

            fare   age     sex
pclass
1       512.3292  35.0  female
2        73.5000  21.0    male
3        69.5500   NaN    male

Таблица: возрастные группы по строкам, класс по столбцам, значение — доля выживших, с итогами по краям:
Ожадю 5 строк

In [57]:
df.pivot_table(
    index='age_group',
    columns='pclass',
    values='survived',
    aggfunc='mean',
    margins=True,
    margins_name='total'
)

pclass            1         2         3     total
age_group
до 16      0.888889  0.904762  0.400000  0.550000
16-32      0.728814  0.428571  0.241379  0.369942
32-64      0.625000  0.424242  0.101266  0.412451
старше 64  0.166667  0.000000  0.000000  0.090909
total      0.655914  0.479769  0.239437  0.406162