Концепект по kaggle 5-6:

In [1]:
import pandas as pd

Data1 = pd.DataFrame({
    'Name': ['Рома', 'Матвей', 'Дима', 'Ливес', 'Ксюша'],
    'Age': [18, 18, 23, 19, 17],
    'Money': [10000000, 10000, 3123, 999, 0],
    'City': ['Санкт-Петербург', 'Москва', 'Казань', 'Гамбург', 'Москва'],
    'IQ': [145, 55, 100, 122, 90]
})
Data1

     Name  Age     Money             City   IQ
0    Рома   18  10000000  Санкт-Петербург  145
1  Матвей   18     10000           Москва   55
2    Дима   23      3123           Казань  100
3   Ливес   19       999          Гамбург  122
4   Ксюша   17         0           Москва   90

In [2]:
Data2 = pd.DataFrame({
    'Name': ['John', 'Max', 'Eduard', 'Kenny', 'Steve'],
    'Age': [24, 15, 32, 15, 17],
    'Money': [12132, 500, 30000000, 1000, 50],
    'City': ['New-York', 'London', 'Turkey', 'London', 'Paris'],
    'IQ': [120, 121, 92, 122, 100]
})

Data2

     Name  Age     Money      City   IQ
0    John   24     12132  New-York  120
1     Max   15       500    London  121
2  Eduard   32  30000000    Turkey   92
3   Kenny   15      1000    London  122
4   Steve   17        50     Paris  100

Концепект по 5:

dtype - показывает тип выбранного столбца пример - reviews.price.dtype
        можно еще использовать сразу для всех столбцов - reviews.dtypes

In [3]:
print(Data1.Money.dtype)
Data2.dtypes

int64

Name       str
Age      int64
Money    int64
City       str
IQ       int64
dtype: object

astype - используется уже не для просмотра типа а для его задавания - reviews.price.astype('float64')

In [4]:
Data1.Money.astype('float64')
print(Data1.Money.dtype)

int64

NaN — это маркер пустоты, который технически всегда является числом с плавающей точкой, то есть имеет тип float64.

In [5]:
for_ex = pd.DataFrame({
    'NaNs': [float('nan'), float('nan'), float('nan')]
})
print(for_ex.NaNs.dtype)

pd.Series([1, 2, float('nan')])

float64

0    1.0
1    2.0
2    NaN
dtype: float64

isnull / notnull - методы предназначенные для работы с NaN'ами - reviews[pd.isnull(reviews.country)]

In [6]:
for_ex[pd.isnull(for_ex.NaNs)]

   NaNs
0   NaN
1   NaN
2   NaN

fillna - метод для replacing missing data - reviews.region_2.fillna("Unknown")
Альтернатива - reviews.taster_twitter_handle.replace("@kerinokeefe", "@kerino")

In [7]:
for_ex.NaNs.fillna('Hello')

0    Hello
1    Hello
2    Hello
Name: NaNs, dtype: object

Концпект по 6:

rename - позволяет менять имена у столбцов или строк
Примеры:
reviews.rename(columns={'points': 'score'})
reviews.rename(index={0: 'firstEntry', 1: 'secondEntry'})

In [8]:
data_coins = Data1.rename(columns={'Money':'coins'})
data_coins

     Name  Age     coins             City   IQ
0    Рома   18  10000000  Санкт-Петербург  145
1  Матвей   18     10000           Москва   55
2    Дима   23      3123           Казань  100
3   Ливес   19       999          Гамбург  122
4   Ксюша   17         0           Москва   90

set_index - ставит колонку в качестве индекса

In [9]:
data_coins2 = Data1.rename(columns={'Money': 'coins'}).set_index('coins')
data_coins2

            Name  Age             City   IQ
coins
10000000    Рома   18  Санкт-Петербург  145
10000     Матвей   18           Москва   55
3123        Дима   23           Казань  100
999        Ливес   19          Гамбург  122
0          Ксюша   17           Москва   90

rename_axis - нужна того чтобы менять атрибуты индексов - reviews.rename_axis("wines", axis='rows').rename_axis("fields", axis='columns')

In [10]:
data_coins3 = data_coins2.rename_axis('money', axis='rows').rename_axis('stats', axis='columns')
data_coins3

stats       Name  Age             City   IQ
money
10000000    Рома   18  Санкт-Петербург  145
10000     Матвей   18           Москва   55
3123        Дима   23           Казань  100
999        Ливес   19          Гамбург  122
0          Ксюша   17           Москва   90

Для того чтобы комбинировать разные датасеты существуют merge() concat() join(), также написано что большинство функций функции merge() можно упростить с помощью функции join() поэтому сфокусируемся на двух оставшихся способах

concat - сжимает датасеты по рядам, а также можно по столбцам при помощи параметра axis=1 - pd.concat([canadian_youtube, british_youtube])

In [11]:
Data3 = pd.concat([Data1, Data2], axis=1)
Data3

,Name,Age,Money,City,IQ,Name,Age,Money,City,IQ
0,Рома,18,10000000,Санкт-Петербург,145,John,24,12132,New-York,120
1,Матвей,18,10000,Москва,55,Max,15,500,London,121
2,Дима,23,3123,Казань,100,Eduard,32,30000000,Turkey,92
3,Ливес,19,999,Гамбург,122,Kenny,15,1000,London,122
4,Ксюша,17,0,Москва,90,Steve,17,50,Paris,100

join - сжимает датасеты по общим индексам и является следующим по сложности - left.join(right, lsuffix='_CAN', rsuffix='_UK')

In [12]:
countries = pd.DataFrame({
    'City': ['Москва', 'Санкт-Петербург', 'Казань', 'Гамбург'],
    'Country': ['Россия', 'Россия', 'Россия', 'Германия']
}).set_index('City')

Data4 = Data1.set_index('City').join(countries, how='left')

Data4

                   Name  Age     Money   IQ   Country
City
Санкт-Петербург    Рома   18  10000000  145    Россия
Москва           Матвей   18     10000   55    Россия
Казань             Дима   23      3123  100    Россия
Гамбург           Ливес   19       999  122  Германия
Москва            Ксюша   17         0   90    Россия

Изначально Матвей и Ксюша дублировались из за того что я прописал Москву в countries дважды, а также у ливеса в был NaN в столбце country из за того что при создании countries я допустил опечатку в названии города Гамбург